server:
  port: 8082

spring:
  application:
    name: resource-service

  datasource:
    url: jdbc:mariadb://localhost:3306/resource_service
    username: admin
    password: admin

  flyway:
    url: jdbc:mariadb://localhost:3306/resource_service?currentSchema=app
    user: admin
    password: admin
